#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
      microservicePath = './modules/base/'
      version = '1.0'
    }

    stages {
        stage('Install, Test, and Build Filter') {
            agent {
                docker 'node:8.12.0-jessie'
            }
            environment {
                CI = 'true'
            }
            steps {
                deleteDir()
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    submoduleCfg: [],
                    userRemoteConfigs: [[url: 'https://github.com/curiousben/Filter-Microservice.git']]
                ])
                dir(microservicePath) {
                    sh 'npm install --only=dev'
                    sh 'npm test'
                    sh 'npm pack'
                }
            }
        }

        stage('Build Docker Image') {
            agent {
                dockerfile {
                  filename 'Dockerfile'
                  dir './docker/1.0'
                  additionalBuildArgs '-t curiousben/filter:v2.0'
                }
            }
            steps {
                sh 'Successfully built the image'
            }
        }
    }
}
