#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
      LIBRARY_PATH = './modules/base/'
      MICROSERVICE = 'filter'
      VERSION = '2.0.0'
    }

    stages {
        stage('Install, Test, and Build Filter') {
            agent {
                docker 'node:8.12.0-jessie'
            }
            environment {
                CI = 'true'
            }
            steps {
                deleteDir()
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    submoduleCfg: [],
                    userRemoteConfigs: [[url: 'https://github.com/curiousben/Filter-Microservice.git']]
                ])
                dir(LIBRARY_PATH) {
                    sh 'npm install --only=dev'
                    sh 'npm test'
                    sh 'npm pack'
                }
            }
        }

        stage('Build Docker Image') {
            agent {
                dockerfile {
                  filename 'Dockerfile'
                  dir './docker/1.0'
                  additionalBuildArgs '--build-args NPM_PACKAGE_VERSION=${env.VERSION} --build-args NPM_PACKAGE=${env.MICROSERVICE}-${env.VERSION}.tgz -t curiousben/${MICROSERVICE}:${VERSION}'
                }
            }
            steps {
                sh 'Successfully built the image'
            }
        }
    }
}
